### ISSUE TITLE
Javascript fails to format java properly

### ISSUE THREAD

**Issue by yolomep** [coleh2/dinneen-coding-time#12]
https://codehsanswers.com/error-almanac/nosuchelementexception

The code doesn't display correctly, instead displays html of what would be the code.

I believe you have included the library to format the code twice, so it attempts to format the formatted code? Or there was a missing /> and something went wrong.

**Comment by chlohal** [comment]
Hi! Thank you so much for letting me know; unfortunately, the website in question (codehsanswers.com) isn't actually based in this repository. I had to shut my website (<https://dinnercodingtime.com>) down due to my teacher's concerns. CodehsAnswers forked the repository, but didn't change the "contact" links, so bug reports are sent here. Please send this issue to <https://github.com/TheSwio/dinner-coding-time>; I think that's the repository for codehsanswers.com.
